[package]
name = "cratetorrent"
version = "0.1.0"
authors = ["mandreyel <mandreyel@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5"
futures = "0.3"
log = "0.4"
# TODO: specify exact features to use to cut down build times
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.2", features = ["codec"] }
serde = "1.0"
serde_bencode = "0.2"
serde_bytes = "0.11"
serde_derive = "1.0"
sha-1 = "0.8"
